import type { Metadata } from "next";
import { Carter_One, Kumbh_Sans } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const carterOne = Carter_One({
  variable: "--font-carter-one",
  weight: "400",
});

const kumbh_sans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reelix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${carterOne.variable} ${kumbh_sans.variable} antialiased overflow-x-hidden`}
      >
        <div className="container max-w-screen-xl mx-auto px-4">
          <Header />
          <hr />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
